name: Bug Report
description: Something is broken or behaves unexpectedly.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please fill out as much as you can.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug.
      placeholder: "When I submit a task with blocked_by, the dependency is never released..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Minimal reproduction
      description: The smallest possible code or sequence of steps that triggers the bug.
      render: python
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      placeholder: "The dependent task should transition to PENDING after the blocker completes."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behaviour
      placeholder: "The dependent task stays PENDING forever."
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: RARK version
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python version
      placeholder: "3.11.8"
    validations:
      required: true
